name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust Nightly
      run: rustup install nightly
      
    - name: Build
      run: cargo +nightly build --verbose
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: linux-bin # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: target/release/rusty-pinger
